import type { NodePropertyTypes, IHttpRequestMethods } from 'n8n-workflow';
import { API_ENDPOINTS } from '../utils/constants';
import { createDisplayOptions, createContactField } from '../utils/helpers';

export const contactsDescription = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options' as NodePropertyTypes,
		noDataExpression: true,
		displayOptions: { show: { resource: ['contacts'] } },
		options: [
			{
				name: 'Get Contacts',
				value: 'getContacts',
				description: 'Get a list of contacts for this administration',
			action: 'Get contacts',
			routing: {
				request: {
					method: 'GET' as IHttpRequestMethods,
					url: API_ENDPOINTS.CONTACTS,
					qs: {
						count: '={{ $parameter["count"] || undefined }}',
						get_invoice_payments: '={{ $parameter["get_invoice_payments"] || undefined }}',
							get_invoices: '={{ $parameter["get_invoices"] || undefined }}',
							get_meta: '={{ $parameter["get_meta"] || undefined }}',
							get_reservation_payment_terms:
								'={{ $parameter["get_reservation_payment_terms"] || undefined }}',
							get_reservations: '={{ $parameter["get_reservations"] || undefined }}',
							limit: '={{ $parameter["limit"] || undefined }}',
							offset: '={{ $parameter["offset"] || undefined }}',
							order: '={{ $parameter["order"] || undefined }}',
							order_by: '={{ $parameter["order_by"] || undefined }}',
							search: '={{ $parameter["search"] || undefined }}',
						},
					},
				},
			},
			{
				name: 'Get Contact',
				value: 'getContact',
				description: 'Get a single contact by ID',
				action: 'Get contact',
				routing: {
					request: {
						method: 'GET' as IHttpRequestMethods,
						url: '=/contacts/{{$parameter["contactId"]}}',
						qs: {
							get_invoice_payments: '={{ $parameter["get_invoice_payments"] || undefined }}',
							get_invoices: '={{ $parameter["get_invoices"] || undefined }}',
							get_meta: '={{ $parameter["get_meta"] || undefined }}',
							get_reservation_payment_terms:
								'={{ $parameter["get_reservation_payment_terms"] || undefined }}',
							get_reservations: '={{ $parameter["get_reservations"] || undefined }}',
						},
					},
				},
			},
			{
			name: 'Add Contact',
			value: 'addContact',
			description:
				'Add either an empty contact or add parameters to a contact. All provided data will be added to the new contact.',
			action: 'Add contact',
			routing: {
				request: {
					method: 'POST' as IHttpRequestMethods,
					url: API_ENDPOINTS.CONTACTS,
					body: {
						first_name: '={{ $parameter["first_name"] || undefined }}',
							last_name: '={{ $parameter["last_name"] || undefined }}',
							gender: '={{ $parameter["gender"] || undefined }}',
							birthday: '={{ $parameter["birthday"] || undefined }}',
							email: '={{ $parameter["email"] || undefined }}',
							phone: '={{ $parameter["phone"] || undefined }}',
							phone_mobile: '={{ $parameter["phone_mobile"] || undefined }}',
							address: '={{ $parameter["address"] || undefined }}',
							address_number: '={{ $parameter["address_number"] || undefined }}',
							city: '={{ $parameter["city"] || undefined }}',
							state: '={{ $parameter["state"] || undefined }}',
							zipcode: '={{ $parameter["zipcode"] || undefined }}',
							country: '={{ $parameter["country"] || undefined }}',
							id_type: '={{ $parameter["id_type"] || undefined }}',
							id_nr: '={{ $parameter["id_nr"] || undefined }}',
							country_origin: '={{ $parameter["country_origin"] || undefined }}',
							company: '={{ $parameter["company"] || undefined }}',
							vat_number: '={{ $parameter["vat_number"] || undefined }}',
							type: '={{ $parameter["type"] || undefined }}',
							meta: '={{ $parameter["extraFields"]?.field?.filter(f => f.value !== "" && f.value !== undefined)?.map(f => ({ key: f.key, value: f.value })) || [] }}',
						},
					},
				},
			},
		],
		default: 'getContacts',
	},

	{
		displayName: 'Contact ID',
		name: 'contactId',
		type: 'string' as NodePropertyTypes,
		required: true,
		description: 'Unique identifier of the contact to retrieve',
		placeholder: '340',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['getContact'] } },
	},
	{
		displayName: 'Count',
		name: 'count',
		type: 'boolean' as NodePropertyTypes,
		description: 'Whether to return only the total number of contacts instead of full details',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Get Invoice Payments',
		name: 'get_invoice_payments',
		type: 'boolean' as NodePropertyTypes,
		description: 'Whether to include invoice payment details for the contact(s)',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},
	{
		displayName: 'Get Invoices',
		name: 'get_invoices',
		type: 'boolean' as NodePropertyTypes,
		description: 'Whether to include related invoices for the contact(s)',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},
	{
		displayName: 'Get Meta',
		name: 'get_meta',
		type: 'boolean' as NodePropertyTypes,
		description:
			'Whether to include meta information about the contact. Note: OTA users have limited access.',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},
	{
		displayName: 'Get Reservation Payment Terms',
		name: 'get_reservation_payment_terms',
		type: 'boolean' as NodePropertyTypes,
		description: 'Whether to include reservation payment term information for the contact(s)',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},
	{
		displayName: 'Get Reservations',
		name: 'get_reservations',
		type: 'boolean' as NodePropertyTypes,
		description: 'Whether to include reservations related to the contact(s)',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},

	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number' as NodePropertyTypes,
		description: 'Maximum number of contacts to return (minimum 1)',
		placeholder: '10',
		typeOptions: { minValue: 1 },
		default: 10,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number' as NodePropertyTypes,
		description: 'Number of contacts to skip before starting to collect results',
		placeholder: '0',
		typeOptions: { minValue: 0 },
		default: 0,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Order',
		name: 'order',
		type: 'options' as NodePropertyTypes,
		description:
			'Sorting order of the returned contacts. Choose ascending (ASC) or descending (DESC).',
		options: [
			{ name: '— None —', value: '' },
			{ name: 'ASC', value: 'asc' },
			{ name: 'DESC', value: 'desc' },
		],
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Order By',
		name: 'order_by',
		type: 'options' as NodePropertyTypes,
		description: 'Field to sort the results by',
		options: [
			{ name: '— None —', value: '' },
			{ name: 'ID', value: 'id' },
			{ name: 'Contact UID', value: 'contact_uid' },
			{ name: 'Contact ID', value: 'contact_id' },
			{ name: 'Admin ID', value: 'admin_id' },
			{ name: 'Chain ID', value: 'chain_id' },
			{ name: 'Status', value: 'status' },
			{ name: 'Name', value: 'name' },
			{ name: 'Created', value: 'created' },
			{ name: 'Type', value: 'type' },
			{ name: 'Last Modified', value: 'last_modified' },
			{ name: 'Last Modified Search', value: 'last_modified_search' },
		],
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Search',
		name: 'search',
		type: 'string' as NodePropertyTypes,
		description: 'Filter contacts by ID or name. Partial matches are allowed.',
		placeholder: 'support@camping.care',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},

	createContactField('first_name', 'First Name', 'First name of the contact', {
		placeholder: 'John',
	}),
	createContactField('last_name', 'Last Name', 'Last name of the contact', {
		required: true,
		placeholder: 'Doe',
	}),
	{
		displayName: 'Gender',
		name: 'gender',
		type: 'options' as NodePropertyTypes,
		description: 'Gender of the contact (used for personalization and reporting)',
		options: [
			{ name: '— None —', value: '' },
			{ name: 'Male', value: 'male' },
			{ name: 'Female', value: 'female' },
			{ name: 'Family', value: 'family' },
		],
		default: '',
		displayOptions: createDisplayOptions('contacts', 'addContact'),
	},
	createContactField('birthday', 'Birthday', 'Birthday of the contact in YYYY-MM-DD format', {
		placeholder: '1990-01-15',
		typeOptions: {
			validation: [
				{
					type: 'regex',
					properties: {
						regex: '^\\d{4}-\\d{2}-\\d{2}$',
						errorMessage: 'Date must be in YYYY-MM-DD format',
					},
				},
			],
		},
	}),
	createContactField('email', 'Email', 'Email address of the contact', {
		required: true,
		placeholder: 'john.doe@example.com',
	}),
	createContactField('phone', 'Phone', 'Primary phone number of the contact', {
		placeholder: '+31123456789',
	}),
	createContactField('phone_mobile', 'Mobile Phone', 'Mobile phone number of the contact', {
		placeholder: '+31612345678',
	}),
	createContactField('address', 'Address', "Street name of the contact's address", {
		placeholder: 'Wilhelminastraat',
	}),
	createContactField('address_number', 'Address Number', "House number of the contact's address", {
		placeholder: '8',
	}),
	createContactField('city', 'City', 'City where the contact resides', { placeholder: 'Denekamp' }),
	createContactField('state', 'State', 'State or province of the contact', {
		placeholder: 'Overijssel',
	}),
	createContactField('zipcode', 'Zipcode', "Postal code of the contact's address", {
		placeholder: '7591TN',
	}),
	{
		displayName: 'Country',
		name: 'country',
		type: 'options' as NodePropertyTypes,
		description: 'Country where the contact resides',
		typeOptions: { loadOptionsMethod: 'getCountriesFromRules' },
		default: '',
		displayOptions: createDisplayOptions('contacts', 'addContact'),
	},
	createContactField(
		'id_type',
		'ID Type',
		'Type of identification document (e.g. Passport, ID Card)',
		{ placeholder: 'Passport' },
	),
	createContactField('id_nr', 'ID Number', 'Identification number of the document', {
		placeholder: 'AB1234567',
	}),
	{
		displayName: 'Country of Origin',
		name: 'country_origin',
		type: 'options' as NodePropertyTypes,
		description: 'Country of origin of the contact',
		typeOptions: { loadOptionsMethod: 'getCountriesFromRules' },
		default: '',
		displayOptions: createDisplayOptions('contacts', 'addContact'),
	},
	createContactField('company', 'Company', 'Company name if the contact represents a business', {
		placeholder: 'Acme Corporation',
	}),
	createContactField(
		'vat_number',
		'VAT Number',
		'VAT number associated with the company (if applicable)',
		{ placeholder: 'NL123456789B01' },
	),
	{
		displayName: 'Type',
		name: 'type',
		type: 'options' as NodePropertyTypes,
		description: 'Type of contact',
		options: [
			{ name: '— None —', value: '' },
			{ name: 'Main Traveler', value: 'main_traveler' },
			{ name: 'Co Traveler', value: 'co_traveler' },
			{ name: 'Booker', value: 'booker' },
		],
		default: '',
		displayOptions: createDisplayOptions('contacts', 'addContact'),
	},
	{
		displayName: 'Extra Fields',
		name: 'extraFields',
		type: 'fixedCollection' as NodePropertyTypes,
		description: 'Add additional metadata fields as key/value pairs',
		placeholder: 'Add Field',
		typeOptions: { multipleValues: true },
		default: { field: [] },
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
		options: [
			{
				displayName: 'Field',
				name: 'field',
				values: [
					{
						displayName: 'Key',
						name: 'key',
						type: 'options' as NodePropertyTypes,
						description: 'Name of the metadata field',
						typeOptions: { loadOptionsMethod: 'getContactFields' },
						default: '',
					},
					{
						displayName: 'Value',
						name: 'value',
						type: 'string' as NodePropertyTypes,
						description: 'Value of the metadata field',
						default: '',
					},
				],
			},
		],
	},
];
