import type { NodePropertyTypes, IHttpRequestMethods } from 'n8n-workflow';

export const contactsDescription = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options' as NodePropertyTypes,
		noDataExpression: true,
		displayOptions: { show: { resource: ['contacts'] } },
		options: [
			{
				name: 'Get Contacts',
				value: 'getContacts',
				description: 'Retrieve all contacts with optional filters, sorting, and metadata',
				action: 'Get contacts',
				routing: {
					request: {
						method: 'GET' as IHttpRequestMethods,
						url: '/contacts',
						qs: {
							count: '={{ $parameter["count"] || undefined }}',
							get_invoice_payments: '={{ $parameter["get_invoice_payments"] || undefined }}',
							get_invoices: '={{ $parameter["get_invoices"] || undefined }}',
							get_meta: '={{ $parameter["get_meta"] || undefined }}',
							get_reservation_payment_terms:
								'={{ $parameter["get_reservation_payment_terms"] || undefined }}',
							get_reservations: '={{ $parameter["get_reservations"] || undefined }}',
							limit: '={{ $parameter["limit"] || undefined }}',
							offset: '={{ $parameter["offset"] || undefined }}',
							order: '={{ $parameter["order"] || undefined }}',
							order_by: '={{ $parameter["order_by"] || undefined }}',
							search: '={{ $parameter["search"] || undefined }}',
						},
					},
				},
			},
			{
				name: 'Get Contact',
				value: 'getContact',
				description: 'Retrieve detailed information of a specific contact by its ID',
				action: 'Get contact',
				routing: {
					request: {
						method: 'GET' as IHttpRequestMethods,
						url: '=/contacts/{{$parameter["contactId"]}}',
						qs: {
							get_invoice_payments: '={{ $parameter["get_invoice_payments"] || undefined }}',
							get_invoices: '={{ $parameter["get_invoices"] || undefined }}',
							get_meta: '={{ $parameter["get_meta"] || undefined }}',
							get_reservation_payment_terms:
								'={{ $parameter["get_reservation_payment_terms"] || undefined }}',
							get_reservations: '={{ $parameter["get_reservations"] || undefined }}',
						},
					},
				},
			},
			{
				name: 'Add Contact',
				value: 'addContact',
				description: 'Create a new contact in the system with optional additional metadata',
				action: 'Add contact',
				routing: {
					request: {
						method: 'POST' as IHttpRequestMethods,
						url: '/contacts',
						body: {
							first_name: '={{ $parameter["first_name"] || undefined }}',
							last_name: '={{ $parameter["last_name"] || undefined }}',
							gender: '={{ $parameter["gender"] || undefined }}',
							birthday: '={{ $parameter["birthday"] || undefined }}',
							email: '={{ $parameter["email"] || undefined }}',
							phone: '={{ $parameter["phone"] || undefined }}',
							phone_mobile: '={{ $parameter["phone_mobile"] || undefined }}',
							address: '={{ $parameter["address"] || undefined }}',
							address_number: '={{ $parameter["address_number"] || undefined }}',
							city: '={{ $parameter["city"] || undefined }}',
							state: '={{ $parameter["state"] || undefined }}',
							zipcode: '={{ $parameter["zipcode"] || undefined }}',
							country: '={{ $parameter["country"] || undefined }}',
							id_type: '={{ $parameter["id_type"] || undefined }}',
							id_nr: '={{ $parameter["id_nr"] || undefined }}',
							country_origin: '={{ $parameter["country_origin"] || undefined }}',
							company: '={{ $parameter["company"] || undefined }}',
							vat_number: '={{ $parameter["vat_number"] || undefined }}',
							meta: '={{ $parameter["extraFields"]?.field?.filter(f => f.value !== "" && f.value !== undefined)?.map(f => ({ key: f.key, value: f.value })) || [] }}',
						},
					},
				},
			},
		],
		default: 'getContacts',
	},

	// === Get Contact / Get Contacts filters ===
	{
		displayName: 'Contact ID',
		name: 'contactId',
		type: 'string' as NodePropertyTypes,
		required: true,
		description: 'Unique identifier of the contact to retrieve',
		placeholder: 'e.g. 1234567',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['getContact'] } },
	},
	{
		displayName: 'Count',
		name: 'count',
		type: 'boolean' as NodePropertyTypes,
		description: 'If enabled, returns only the total number of contacts instead of full details',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Get Invoice Payments',
		name: 'get_invoice_payments',
		type: 'boolean' as NodePropertyTypes,
		description: 'If enabled, includes invoice payment details for the contact(s)',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},
	{
		displayName: 'Get Invoices',
		name: 'get_invoices',
		type: 'boolean' as NodePropertyTypes,
		description: 'If enabled, includes related invoices for the contact(s)',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},
	{
		displayName: 'Get Meta',
		name: 'get_meta',
		type: 'boolean' as NodePropertyTypes,
		description:
			'If enabled, includes meta information about the contact. Note: OTA users have limited access.',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},
	{
		displayName: 'Get Reservation Payment Terms',
		name: 'get_reservation_payment_terms',
		type: 'boolean' as NodePropertyTypes,
		description: 'If enabled, includes reservation payment term information for the contact(s)',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},
	{
		displayName: 'Get Reservations',
		name: 'get_reservations',
		type: 'boolean' as NodePropertyTypes,
		description: 'If enabled, includes reservations related to the contact(s)',
		default: false,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts', 'getContact'] } },
	},

	// === Pagination & Sorting ===
	{
		displayName: 'Limit',
		name: 'limit',
		type: 'number' as NodePropertyTypes,
		description: 'Maximum number of contacts to return (minimum 1)',
		typeOptions: { minValue: 1 },
		default: 10,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Offset',
		name: 'offset',
		type: 'number' as NodePropertyTypes,
		description: 'Number of contacts to skip before starting to collect results',
		typeOptions: { minValue: 0 },
		default: 0,
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Order',
		name: 'order',
		type: 'options' as NodePropertyTypes,
		description: 'Select the sorting order of the returned contacts. — None — will not sort.',
		options: [
			{ name: '— None —', value: '' },
			{ name: 'ASC', value: 'asc' },
			{ name: 'DESC', value: 'desc' },
		],
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Order By',
		name: 'order_by',
		type: 'options' as NodePropertyTypes,
		description: 'Select the field to sort the results by. — None — leaves results unsorted.',
		options: [
			{ name: '— None —', value: '' },
			{ name: 'ID', value: 'id' },
			{ name: 'Contact UID', value: 'contact_uid' },
			{ name: 'Contact ID', value: 'contact_id' },
			{ name: 'Admin ID', value: 'admin_id' },
			{ name: 'Chain ID', value: 'chain_id' },
			{ name: 'Status', value: 'status' },
			{ name: 'Name', value: 'name' },
			{ name: 'Created', value: 'created' },
			{ name: 'Type', value: 'type' },
			{ name: 'Last Modified', value: 'last_modified' },
			{ name: 'Last Modified Search', value: 'last_modified_search' },
		],
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},
	{
		displayName: 'Search',
		name: 'search',
		type: 'string' as NodePropertyTypes,
		description: 'Filter contacts by ID or name. Partial matches are allowed.',
		placeholder: 'Search by ID or name',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['getContacts'] } },
	},

	// === Add Contact ===
	{
		displayName: 'First Name',
		name: 'first_name',
		type: 'string' as NodePropertyTypes,
		description: 'First name of the contact',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Last Name',
		name: 'last_name',
		type: 'string' as NodePropertyTypes,
		required: true,
		description: 'Last name of the contact',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Gender',
		name: 'gender',
		type: 'options' as NodePropertyTypes,
		description: 'Gender of the contact (used for personalization and reporting)',
		options: [
			{ name: '— None —', value: '' },
			{ name: 'Male', value: 'male' },
			{ name: 'Female', value: 'female' },
			{ name: 'Family', value: 'family' },
		],
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Birthday',
		name: 'birthday',
		type: 'string' as NodePropertyTypes,
		description: 'Birthday of the contact in YYYY-MM-DD format',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Email',
		name: 'email',
		type: 'string' as NodePropertyTypes,
		required: true,
		description: 'Email address of the contact',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Phone',
		name: 'phone',
		type: 'string' as NodePropertyTypes,
		description: 'Primary phone number of the contact',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Mobile Phone',
		name: 'phone_mobile',
		type: 'string' as NodePropertyTypes,
		description: 'Mobile phone number of the contact',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Address',
		name: 'address',
		type: 'string' as NodePropertyTypes,
		description: "Street name of the contact's address",
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Address Number',
		name: 'address_number',
		type: 'string' as NodePropertyTypes,
		description: "House number of the contact's address",
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'City',
		name: 'city',
		type: 'string' as NodePropertyTypes,
		description: 'City where the contact resides',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'State',
		name: 'state',
		type: 'string' as NodePropertyTypes,
		description: 'State or province of the contact',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Zipcode',
		name: 'zipcode',
		type: 'string' as NodePropertyTypes,
		description: "Postal code of the contact's address",
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Country',
		name: 'country',
		type: 'options' as NodePropertyTypes,
		description: 'Country where the contact resides',
		typeOptions: { loadOptionsMethod: 'getCountriesFromRules' },
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'ID Type',
		name: 'id_type',
		type: 'string' as NodePropertyTypes,
		description: 'Type of identification document (e.g. Passport, ID Card)',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'ID Number',
		name: 'id_nr',
		type: 'string' as NodePropertyTypes,
		description: 'Identification number of the document',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Country of Origin',
		name: 'country_origin',
		type: 'options' as NodePropertyTypes,
		description: 'Country of origin of the contact',
		typeOptions: { loadOptionsMethod: 'getCountriesFromRules' },
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Company',
		name: 'company',
		type: 'string' as NodePropertyTypes,
		description: 'Company name if the contact represents a business',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'VAT Number',
		name: 'vat_number',
		type: 'string' as NodePropertyTypes,
		description: 'VAT number associated with the company (if applicable)',
		default: '',
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
	},
	{
		displayName: 'Extra Fields',
		name: 'extraFields',
		type: 'fixedCollection' as NodePropertyTypes,
		description: 'Add additional metadata fields as key/value pairs',
		placeholder: 'Add Field',
		typeOptions: { multipleValues: true },
		default: { field: [] },
		displayOptions: { show: { resource: ['contacts'], operation: ['addContact'] } },
		options: [
			{
				displayName: 'Field',
				name: 'field',
				values: [
					{
						displayName: 'Key',
						name: 'key',
						type: 'options' as NodePropertyTypes,
						description: 'Name of the metadata field',
						typeOptions: { loadOptionsMethod: 'getContactFields' },
						default: '',
					},
					{
						displayName: 'Value',
						name: 'value',
						type: 'string' as NodePropertyTypes,
						description: 'Value of the metadata field',
						default: '',
					},
				],
			},
		],
	},
];
